### ISSUE TITLE
Invalid Tectonic License problem

### ISSUE THREAD

**Issue by lechat** [coreos/tectonic-forum#180]
### Tectonic Version 
1.7.1-tectonic.2

### Environment
AWS

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS vanilla install with all defaults

### Expected Behavior
Working Cluster Console

### Actual Behavior
Upon access to console this message is shown:

  Invalid Tectonic License
  Error parsing license as jwt: invalid character '%' looking for beginning of value

  Please login to account.coreos.com to get your latest license. You may need to contact sales to renew.

All attempts to re-enter license result in this error message:

Invalid license encoding

### Reproduction Steps
  1. Start browser based AWS install
  2. Accept all defaults, enter license/pull details by clicking on "upload file"
  3. Wait till console is available
  4. See license error above

**Comment by robszumski** [comment]
Sorry that you ran into this. Can you describe how you obtained the license?

**Comment by lechat** [comment]
Registered on website and got it from my profile. Is there another way to obtain it?

**Comment by robszumski** [comment]
@lechat Checked on your license from our side, seems ok. Are there any browser errors you are seeing while the installer runs?

**Comment by lechat** [comment]
I started from scratch again and now it worked fine. Not sure why it happened first time...

**Comment by kim0** [comment]
@robszumski .. I just hit a similar problem. I remember copy/pasting the license into some editor .. saving it locally .. then copy pasting from that into the file that I actually deployed from.

I was getting numerous weird issues (console not opening, license error flashes ...). I traced the problem to a LineFeed character (ascii 0a) at the end of the license file. It somehow got there (some editor probably put it). It was a bit hard because even vim would not show it. I had to `hexdump -C` to view it. I see two bugs here
 * Tectonic is not resilient and does not show a proper error message when faced with an invalid license. Instead it flashes some yellow error, then reloads the screen & throws me back at the login page in an infinite loop
 * Extra characters like CR-LF or space or enter ... should be handled as they'll happen a lot when copy pasting
