### ISSUE TITLE
tectonic-identity-controller - how do we preserve tokens across pod reschedules?

### ISSUE THREAD

**Issue by lazypower** [coreos/tectonic-forum#191]
### Environment 

What hardware/cloud provider/hypervisor is being used with Tectonic? AWS VPC

### Expected Behavior  
 The ability to have an identity pod crash and come back without needing to re-fetch kubeconfig with a fresh token.

### Actual Behavior 

If the identity-controller is rescheduled, scaled, or any event affecting the IDMC happens it invalidates existing refresh tokens forcing the end user to re-fetch kubeconfig and re-enter the kubeconfig file management steps.

### Reproduction Steps

 1. Deploy tectonic. 
 2. Download your kubeconfig and verify it works
 3. Scale the identity-controller (or kubectl delete and let the deployment scale back up) 
 4. Attempt to use the previously fetched kubeconfig. The end user will have to re-fetch a new refresh token in order to use their kubeconfig.

**Comment by kbrwn** [comment]
@chuckbutler Could you elaborate on why this behavior should be expected? It seems reasonable for users to re-fetch a kubeconfig file in the event of a configuration change or failure of the identity service.

**Comment by chuckbutler** [comment]
@kbrwn If this is known and expected behavior I suppose there's nothing more to do here.

The usability papercut of systems that rely on these kubeconfig files (read: a dept of several hundred developers working in capacity of dev, qa, and staging contexts) having to re-fetch a config and re-merge into their master kubeconfig file is not a stellar end-user story because the identity pod migrated and generated a new nonce for the refresh tokens.

Its my opinion that if the identity controller were to be upgraded or whole-sale removed it makes sense then, but an override env var would be welcome preventing departments from having to re-fetch and re-merge kubeconfig files because the system hiccup'd.  Its then an explicit action by the administrative user.

I suppose this does expose a potential security risk if your identity management service is exposed to outside traffic, but in our context we're primarily running with limited access to VPN hosts and specific white listed CIDR's as we're carrying a patch locally:  https://github.com/coreos/tectonic-installer/pull/1508/files which limits access to these endpoints to whitelisted IP's to begin with. Layers do help, but are a usability papercut while we're still suffering from errant behavior from our HA masters  illustrated in: #189

**Comment by robszumski** [comment]
Thanks for this feedback @chuckbutler, we are evaluating better options for managing kubeconfigs, especially as folks have multiple clusters.
