### ISSUE TITLE
Broken Download Links on coreos

### ISSUE THREAD

**Issue by ThomasThelen** [coreos/tectonic-forum#299]
The download link given in the [tutorial](https://coreos.com/tectonic/docs/latest/tutorials/sandbox/install.html) is [broken](https://coreos.com/tectonic/sandbox/).

This came up on [Stack Overflow](https://stackoverflow.com/questions/50475530/cannot-download-tectonic-sandbox/50476251#50476251)

**Comment by rushins** [comment]
i think Redhat strategy to move to  openshift may be disrupting. not a clue but i dont see kubernetes 1.9 as mentioned in march  is not available even today ?

**Comment by robszumski** [comment]
The sandbox has been lagging behind the regular Tectonic releases, and with the acquisition, we don't plan to update it further, which is why the download has been removed. All of the docs were supposed to have been removed, but clearly that is not the case ;)

If you want to check out the [old version](https://releases.tectonic.com/sandbox/tectonic-sandbox-1.7.5-tectonic.1.zip) (1.7.5) you can, but note that it doesn't reflect the latest Tectonic. If you'd like to check that out, I recommend [using AWS](https://coreos.com/tectonic/docs/latest/install/aws/aws-terraform.html) with 1.9.6, which was just released today.

You can also check out [Minishift](https://github.com/minishift/minishift), a local version of OpenShift. For more info on how Tectonic technology is being integrated, check out [this blog post](https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift).
